id: video_1
time_limit: 120
proxy: 127.0.0.1:8001
enable_warcprox_features: true
remember_outlinks: true
ignore_robots: true
scope:
  accepts:
  - url_match: SURT_MATCH
    value: https://(com,youtube,
  - url_match: SURT_MATCH
    value: https://(com,googlevideo,
  - url_match: SURT_MATCH
    value: https://(com,ytimg,
warcprox_meta:
    warc-prefix: video
    stats:
        buckets:
        - video-stats
metadata: {}
seeds:
  - url: https://www.youtube.com/watch?v=dqG0VILi3gs
    scope:
        max_hops: 1